### ISSUE TITLE
Would dropdowns have scrollbars if needed?

### ISSUE THREAD

**Issue by Jeff-Stammler** [team3663/Scouting-App#123]
Future proofing, but I don't know the maximum # of options we'd currently support in a dropdown.  If we had more (say on "submit", looking for past matches to transmit data) would scroll bars appear automatically?  Is that something we need to (dynamically) specify?

**Comment by AdrielStammler** [comment]
I know that the context menus won’t scroll and just won’t be able to access the items off the page.

**Comment by EllaNorby** [comment]
You can add the ability to scroll to a Spinner.

**Comment by Jeff-Stammler** [comment]
Turns out you can still scroll the spinner - even without scroll bars.  So i'm not sure how necessary this is, or even if it's needed.  The tablets won't have a mouse, and you're not going to scroll the scroll-bar with you finger on a tablet.

**Comment by Jeff-Stammler** [comment]
Spinner is easy, but the scroll bar doesn't look so obvious.  It's much hard for a ContextMenu. You need to create your own customer ContextMenu.  I don't think it's worth the effort for such little gain.  The custom piece makes it a lot less desirable as well.
