### ISSUE TITLE
Can the multi-select only clear the checkboxes without closing the dropdown?

### ISSUE THREAD

**Issue by Jeff-Stammler** [team3663/Scouting-App#130]
If possible, it's more intuitive.  You can clear your selections, then hit "OK".  But since there's an "OK" and "Cancel" i assumed "Clear All" would reset the selections and allow me to choose new ones (without needing to reopen the dialog).

Of course if this can be done, then "Clear All" followed by "Cancel" needs to keep the previously selected options.  :)

**Comment by AdrielStammler** [comment]
I did some with dialogs and every button automatically closes when you click it after running your code. And I don’t think you can disable it.

**Comment by Jeff-Stammler** [comment]
If someone can confirm that, then we'll just live with it.  But it'd be good to check.
