### ISSUE TITLE
Only One Achievement Showing

### ISSUE THREAD

**Issue by AdrielStammler** [team3663/Scouting-App#298]
I ran the app and tested getting some of the achievements, and all I did was run through a match where I scout us, and I didn't do anything else. When I got to submit page, it popped up the Orphaned achievement because we started with a note, and I didn't do anything. But I didn't get the "scouted us" achievement.

**Comment by Jeff-Stammler** [comment]
@AdrielStammler I just tried it and got both.  Is your AVD set to be a device from 3663?

**Comment by AdrielStammler** [comment]
Actually, this is only the case if you choose to override the team number.

**Comment by AdrielStammler** [comment]
Which is what I was doing.
